# Site settings
title: Intersect training theme             # The title of your site
description: "A master repository for layout and styling of Intersect training courses"   # A short description of your site
contactmessage: "We value your feedback:"   # Call to action message in the footer
surveyurl: "http://yoursurvey.com"          # The URL of a feedback or interest survey
email: your_email@email.com                 # Your email contact address
licence: "This theme is released under an MIT License. The Learn and Intersect logos are copyright (c) of Intersect Australia Ltd 2018. All rights reserved"      # A statement of the licencing conditions of your site
baseurl: "/intersect-training-theme"                                 # the subpath of your site, e.g. /blog
url: ""                                     # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge
